pydata/bottleneck

- bottleneck/src/template/move.pyx
> ENH: Use Welford's method for move_std

- appveyor.yml
- tools/appveyor/conda_manager.py
- tools/appveyor/conda_setup.py
- tools/appveyor/conda_wrapper.py
- tools/appveyor/windows_sdk.cmd
Add continuous integration on AppVeyor, i.e., 32bit and 64bit Windows, to bottleneck. Builds the package using MSVC and runs the test suite.
> Appveyor Support

- appveyor.yml
- tools/appveyor/conda_setup.py
- tools/appveyor/conda_wrapper.py
Depend on the correct Miniconda installation depending on desired platform architecture. Cleans up the wrapper class slightly.
> Build arch

- .travis.yml
Just a quick fix to set the image only where needed.
> add osx image to matrix only where osx is built

- README.rst
- setup.py
Update maintainer information to reflect https://github.com/pydata/bottleneck/issues/209
> DOC: update maintainer

- bottleneck/src/bn_template.py
- setup.cfg
- setup.py
Be a little smarter about only compiling when necessary by looking at template vs output timestamps
>  BLD: only regenerate templates if they have been modified 

- bottleneck/src/iterators.h
This is to support the switch to working with arrays of type `npy_{dtype}` rather than working with `char *` and casting as needed. This switch will allow compilers to more effectively optimize a large number of cases.
> CLN: expose the element stride in iterators.h

- .travis.yml
- LICENSES/PANDAS_LICENSE
- RELEASE.rst
- doc/source/conf.py
- doc/sphinxext/announce.py
- doc/sphinxext/contributors.py
Thank you to everyone who has contributed over the years!
The release notes have been updated to list every contributor to a given release, with extra highlighting if it's their first contribution. Publication will probably take another week or two as I figure out where I'd like the documentation to be hosted going forward.
> Automatically cite our contributors in the release notes

- appveyor.yml
Upgrade pip on appveyor to fix broken builds
> BLD: Appveyor fix

- bottleneck/tests/nonreduce_axis_test.py
- bottleneck/tests/reduce_test.py
Add test cases for some corner cases
> Test coverage

- doc/source/conf.py
- readthedocs.yml
Take another swing, this time using the v2 API
> DOC: use RTD.yml v2

- setup.py
Update the PyPI classifiers in preparation for release
> DOC: update PyPI classifiers

- RELEASE.rst
Release v1.3.0 and update documentation.
> RLS: Release v1.3.0

- RELEASE.rst
- bottleneck/tests/memory_test.py
Create a release for the memory leak fix and include a regression test to prevent re-occurrence.
> RLS: Bottleneck 1.3.1

- RELEASE.rst
Update docs to kick off 1.4 development
> DOC: update documentation for start of 1.4 development

- bottleneck/src/bn_config.py
- bottleneck/src/bottleneck.h
- bottleneck/src/iterators.h
- bottleneck/src/move_median/move_median.c
- bottleneck/src/move_median/move_median.h
- bottleneck/src/move_median/move_median_debug.c
- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/nonreduce_template.c
Fix a variety of minor style issues that have been making linters unhappy
> Miscellaneous cleanup

- README.rst
- doc/source/conf.py
- doc/source/index.rst
Switch to a cleaner theme and provide a bit better of an introduction to people coming across Bottleneck for the first time.
> Change Sphinx theme to alabaster

- bottleneck/src/move_median/move_median_debug.c
- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/reduce_template.c
> CLN: whitespace cleanup in C templates

- .travis.yml
- doc/source/bottleneck.rst
- doc/source/index.rst
- setup.cfg
The documentation test has been silently failing. Change configuration to throw an exception on warnings and fix an existing warning.
> Fix doc test

- bottleneck/src/reduce_template.c
Largest benefits seen by `float32` using `clang` but beneficial across the board.
```
[eaf2bb00]       [e95171d0]
<anynan_reduce~1>       <nanmin_reduce>
-        888±20ns         799±30ns     0.90  reduce.Time1DReductions.time_nanmin('int64', (1000,)) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-     1.02±0.02μs         882±20ns     0.87  reduce.Time1DReductions.time_nanmin('float64', (1000,)) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-      6.49±0.1ms       5.51±0.2ms     0.85  reduce.Time1DReductions.time_nanmin('float64', (10000000,)) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        661±20μs         544±30μs     0.82  reduce.Time2DReductions.time_nanmin('float64', (1000, 1000), 'F', …
```
> PERF: significantly improve performance for nanmin/max for axis=None

- bottleneck/src/reduce_template.c
Minor improvements to `nanmin`/`nanmax` for `axis=0/1` on float data. Also fix issue breaking Windows builds.
> Nanmin axis

- bottleneck/benchmark/autotimeit.py
- bottleneck/src/bn_template.py
Now that we're Py3 only, start implementing type annotations.
> Add mypy typing to autotimeit and bn_template

- bottleneck/src/reduce_template.c
Large speedups via vectorization for allnan
```
$ asv compare HEAD^ HEAD -s --sort ratio
Benchmarks that have improved:
[a72e0d23]       [a8565469]
<allnan~1>       <allnan>  
-        779±10μs         707±10μs     0.91  reduce.TimeAllNan2D.time_allnan('float64', (1000, 1000), 'F', None, 'slow') [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-     3.85±0.09μs      3.49±0.04μs     0.91  reduce.TimeAllNan2D.time_allnan('float32', (1000, 1000), 'C', 0, 'fast') [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-         776±7μs          696±3μs     0.90  reduce.TimeAllNan2D.time_allnan('float64', (1000, 1000), 'C', None, 'slow') [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-      1.14±0.4ms          894±6μs     0.78 …
```
> PERF: improve allnan reduction performance by up to 4x on float32

- bottleneck/tests/reduce_test.py
Hypothesis seems to only generate C arrays by default - inject F arrays as well into the testing. Also restrict the types to ones we specifically use to increase testing efficiency.
> TST: extend hypothesis testing to Fortran-order arrays

- .github/workflows/pythonpackage.yml
- .gitignore
- bottleneck/src/bn_template.py
- bottleneck/src/nonreduce_template.c
- bottleneck/tests/test_template.py
> FIX: ensure #line statements have posix-style paths on windows, fix

- .travis.yml
- tools/travis/bn_setup.sh
- tools/travis/conda_install.sh
- tools/travis/conda_setup.sh
Added arm64 test support in travis-ci.
Modified environment creation by using archiconda instead of miniconda as miniconda is not supported in arm64 currently.
> Added arm64 jobs in Travis-CI

- bottleneck/src/bn_config.py
- bottleneck/src/bottleneck.h
- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/reduce_template.c
Leverage `__builtin_isnan()`, `_isnan()` and `isnan()` as much as possible over `x != x`
> CLN: add bn_isnan() to leverage __builtin_isnan() where possible

- RELEASE.rst
- pyproject.toml
Mostly incorporating #325 and related docs
> Merge 1.3.2 changes

- bottleneck/src/reduce_template.c
Some slight slowdowns in the other axis for `gcc7`, but otherwise broad speedups:
```
$ asv compare HEAD^ HEAD -s --sort ratio  --only-changed | grep -v fast | grep -v int
[3d1cb0a2]       [0386185c]
-         652±8μs          515±9μs     0.79  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'F', 0, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-9-CXXg++-9]
-        651±30μs         506±10μs     0.78  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'F', 0, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-8-CXXg++-8]
-        665±20μs         508±20μs     0.76  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'C', 1, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-9-CXXg++-9]
-        772±10μs        578±100μs     0.75 …
```
> PERF: extend SSE2 operations to anynan/allnan in contiguous axis case

- bottleneck/src/bn_config.py
Add some types to `bn_config.py`, upstream fixes to `Config` pending https://github.com/python/typeshed/pull/3739 approval
> TYP: add annotations to bn_config.py

- bottleneck/src/bottleneck.h
- bottleneck/src/iterators.h
- bottleneck/src/move_median/move_median.c
- bottleneck/src/move_median/move_median_debug.c
- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/reduce_template.c
- setup.py
Miscellaneous cleanup based on `cppcheck` output. `asv` reports no significant changes.
> Cleanup variable scoping and naming

- .clang-format
- .github/workflows/pythonpackage.yml
- Makefile
- bottleneck/src/bottleneck.h
- bottleneck/src/iterators.h
- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/nonreduce_template.c
- bottleneck/src/reduce_template.c
Ensure our `.c` and `.h` files are consistently formatted using `clang-format`. Also require that any PRs pass this test so we have consistent formatting.
> Configure clang-format for .c and .h files and add tests

- bottleneck/src/move_template.c
- bottleneck/src/nonreduce_axis_template.c
- bottleneck/src/nonreduce_template.c
- bottleneck/src/reduce_template.c
> BUG: decref array when falling back to slow call

- .github/workflows/ci.yml
- setup.py
Fix the setup script to install the data for tests.  This is necessary
for test_template.py to pass.
> BUG: install test data

- bottleneck/slow/move.py
Use explicit boolean c type. Fixes #402
> [slow/move] fix np.bool deprecation

- .github/workflows/ci.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> MNT: Add Python 3.11 to GHA

- doc/source/reference.rst
> DOC: Update reference.rst

- .github/renovate.json
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/marketplace/renovate
> MNT: Enable Renovate

- .github/workflows/ci.yml
- bottleneck/slow/move.py
> BUG: Fix build/tests with numpy 1.24

- README.rst
> Update Python version support and install docs in README
