bottleneck/src/template/move.pyx
Richard Harter's webpage was taken offline after his passing in 2012. Fortunately, the whole site was cloned and put back online at http://www.richardhartersworld.com/, this corrects the link to his original code.
=> Broken link in comment

setup.py
Second attempt at fixing issue #106.
I had problems with sys.path and install vs. develop installs, but I think I figured it out at last. I now trust tox for testing.
The top_level.txt file is now correct:
```
$ cat Bottleneck.egg-info/top_level.txt 
bottleneck
```
And this is the tox output after I added a py35_np191 testenv as I don't have a python3.4 installation on my machine:
```
$ tox
GLOB sdist-make: /Users/amici/devel/bottleneck/setup.py
py27_np191 inst-nodeps: /Users/amici/devel/bottleneck/.tox/dist/Bottleneck-1.1.0.dev0.zip
py27_np191 runtests: PYTHONHASHSEED='2016462959'
py27_np191 runtests: commands[0] | /Users/amici/devel/bottleneck/.tox/py27_np191/bin/python /Users/amici/devel/bottleneck/tools/test-installed-bottleneck.py
Running unit tests for bottleneck
NumPy version 1.9.1 …
```
=> Minimal change in metadata that fixes the top_level.txt file

.travis.yml, ci/travis/bn_setup.sh, ci/travis/conda_install.sh, ci/travis/conda_setup.sh
I left in Python 3.4 since it's the standard version for Debian and Ubuntu (which I'm using currently). Not sure about the intricacies of differences between 3.4 and 3.5 but seems that there's no harm done. Everything runs fine except for flake8 which fails on some of the test files. You can either change those files or adjust the way that flake8 runs (by excluding test files in `setup.cfg`, for example).
=> Expand testing to sdist and flake8

bottleneck/csrc/move_median.c, bottleneck/csrc/move_median.h
I took the [definition of NAN from Cython](https://github.com/cython/cython/blob/master/Cython/Utility/ModuleSetupCode.c#L309).
See also https://github.com/kwgoodman/bottleneck/issues/128
=> Fix compile errors with msvc9 and msvc10

doc/source/conf.py
`file()` is no longer a built-in in Python 3. It is better to just use a single call to `open` chained with a `read`.
=> Enable build of docs with Python 3

RELEASE.rst, bottleneck/slow/move.py
Fixes https://github.com/kwgoodman/bottleneck/issues/194
These show up when using the "slow" versions of moving window functions, e.g.,
FutureWarning: Using a non-tuple sequence for multidimensional indexing is
deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this
will be interpreted as an array index, `arr[np.array(seq)]`, which will
result either in an error or a different result.
nidx1 = n[idx1]
Let me know if you'd like me to add a test here (but I think these lines already have coverage).
=> Silence NumPy warnings about indexing with non-tuples

RELEASE.rst, bottleneck/src/move_template.c, bottleneck/src/nonreduce_axis_template.c, bottleneck/src/nonreduce_template.c, bottleneck/src/reduce_template.c
All bottleneck functions leak memory, as reported in #201, when the input is not a numpy array.
=> Memory leak when input is not a numpy array

MANIFEST.in, pyproject.toml
The use of ``setup_requires`` to declare build-time dependencies is problematic because it is honored by setuptools rather than pip, which means that it doesn't ignore numpy pre-releases. This in turn is causing issues at the moment because when installing bottleneck into a clean environment, it is build against numpy 1.16rc2 and then numpy 1.15 is installed, which then causes bottleneck to not work (since there was a change in API between numpy 1.15 and 1.16). For a more in-depth description of this issue, see [this post I made on numpy-discussion](https://mail.python.org/pipermail/numpy-discussion/2019-January/079097.html).
In any case, projects should now start declaring build-time dependencies using a ``pyproject.toml`` file as described in [PEP …
=> Add a pyproject.toml file declaring build-time dependencies

setup.py
Running `pip wheel ./`  in the source checkout with pip>19.0 fails with a `AttributeError: 'dict' object has no attribute __NUMPY_SETUP__`
Depending on how the setup.py script is executed (as `__main__` or not) `__builtins__` in the global namespace can be a dictionary or a module (https://docs.python.org/3/library/builtins.html says it can be either and that this is an cpython implementation detail).
Fixed by an explicit import.
=> Fix build error `AttributeError: 'dict' object has no attribute ...`

bottleneck/src/move_template.c
Closes https://github.com/pydata/bottleneck/issues/207
=> CLN: remove tautological comparison for ints in move_rank

asv_bench/asv.conf.json, asv_bench/benchmarks/reduce.py
Add a basic `asv` setup covering `bottleneck.reduce` for the following combinations:
- Python 2.7 and 3.7
- Both `gcc` and `clang`
- Both `C` and `F` ordering
- All supported types
- Both 1-D and 2-D arrays
- Also spanning 10^3 to 10^7 elements
The good (and bad) news is that this suite identifies a decent number of regressions and performance discrepancies. Current output available at https://qwhelan.github.io/bottleneck/
=> BENCH: add initial asv suite covering reductions

.travis.yml, appveyor.yml, bottleneck/__init__.py, bottleneck/_pytesttester.py, bottleneck/tests/input_modification_test.py, bottleneck/tests/list_input_test.py, bottleneck/tests/move_test.py, bottleneck/tests/nonreduce_axis_test.py, bottleneck/tests/nonreduce_test.py, bottleneck/tests/reduce_test.py, bottleneck/tests/scalar_input_test.py, tools/test-installed-bottleneck.py, tools/travis/bn_setup.sh, tox.ini
The `nose` project has been unmaintained for several years now, so switch to `py.test` just like `numpy` has.
=> [TST] Switch from nose to pytest

asv_bench/benchmarks/reduce.py, bottleneck/src/bottleneck.h, bottleneck/src/reduce_template.c
Enable BN_OPT_3 for anynan/allnan for a 2x speedup. `asv` results:
```
$ asv compare HEAD^^ HEAD -s --sort ratio --only-changed
[f44d5ece]       [c77a69d0]
<o3~2>           <o3>      
-         950±4ns         541±30ns     0.57  reduce.TimeAllNan2D.time_allnan('int32', (1000, 1000), 'C', 0, 'fast') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-         960±9ns         539±10ns     0.56  reduce.TimeAllNan2D.time_allnan('int64', (1000, 1000), 'F', 1, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-         964±5ns         540±20ns     0.56  reduce.TimeAllNan2D.time_allnan('int32', (1000, 1000), 'C', 1, 'fast') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        949±10ns          530±8ns     0.56  reduce.TimeAllNan2D.time_allnan('int32', (1000, 1000), 'F', …
```
=> PERF: Add BN_OPT_3 to allow enabling -O3 at the function level 

bottleneck/src/nonreduce_template.c
This PR enables vectorization in `replace`, leading to a 4x speedup for `np.int32` and smaller speedups for `np.int64` and `np.float32`.
```
[0c710b14]       [af7c2142]
<replace~1>       <replace> 
-     1.03±0.01ms         650±10μs     0.63  nonreduce.TimeReplace2D.time_replace('int64', (1000, 1000), 'C') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-     1.06±0.01ms          667±6μs     0.63  nonreduce.TimeReplace2D.time_replace('int64', (1000, 1000), 'F') [T470/conda-py2.7-numpy1.16-CCgcc-CXXg++]
-     1.03±0.01ms         648±10μs     0.63  nonreduce.TimeReplace2D.time_replace('int64', (1000, 1000), 'F') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-     1.07±0.05ms          662±9μs     0.62  nonreduce.TimeReplace2D.time_replace('int64', (1000, 1000), …
```
=> PERF: speed up replace() up to 4x via more explicit typing on input array

bottleneck/src/bn_config.py, bottleneck/src/bottleneck.h, bottleneck/src/iterators.h, bottleneck/src/move_median/move_median.c, bottleneck/src/move_median/move_median.h, bottleneck/src/move_template.c, bottleneck/src/nonreduce_axis_template.c, bottleneck/src/nonreduce_template.c, bottleneck/src/reduce_template.c, setup.py
We had previously copied numpy's `inline` logic for _two_ separate variables `BN_INLINE` and `MM_INLINE`. This PR proposes eliminating both in favor of another numpy approach: `#define inline`
To do this, we pull in more of numpy's compiler feature detection code, with some cleanup so successful tests don't throw off tons of warnings due to bad syntax.
Also, declare an unspecified dependency in `setup.py` that was surfaced by this cleanup.
=> CLN: automatically determine correct "inline" alias and define in bn_config.h

RELEASE.rst, doc/source/conf.py
Use the `sphinxext.ext.extlinks` module to provide actual links to the github issues, rather than just an issue number
=> DOC: turn all github issue references into actual links

bottleneck/__init__.py
Not a full answer to the build-pinning question, but at least provide users a best guess as to how to resolve a numpy version conflict if encountered.
Thanks to @stas00 for documenting workarounds in #204
=> DOC: provide relevant info on how to fix numpy version skew if encountered

pyproject.toml, tools/travis/conda_install.sh
Match how `scipy` and `pandas` are handling the `numpy` pinning issue, including the AIX patch mentioned here: https://github.com/scipy/scipy/pull/10431
Pinning to an older version of numpy appears to work just fine with local testing, given the api is generally backwards compatible. This may change in a future release, which will require a new release from `bottleneck` - I'm fine with doing that as needed.
=> BLD: pin numpy in pyproject.toml on a per-python-version basis

bottleneck/src/reduce_template.c
When computing `bn.median(arr, axis=None)` for `arr = np.array(..., order='F')` we currently call `np.ravel()`, which copies the data into C-order. Since `axis=None`, we're computing the median for all of the data and C-ordering therefore does not matter.
Eliminating the superfluous copy gives up to a 2x speedup:
```
[7ff5451a]       [9b20723c]
<no_ravel_median~1>       <no_ravel_median>
-     5.20±0.08ms       4.70±0.1ms     0.90  reduce.Time2DReductions.time_median('int64', (1000, 1000), 'C', 1) [T470/conda-py2.7-numpy1.16-CCgcc-CXXg++]
-      6.74±0.1ms      6.07±0.08ms     0.90  reduce.Time2DReductions.time_nanmedian('int64', (1000, 1000), 'C', 0) [T470/conda-py2.7-numpy1.16-CCgcc-CXXg++]
-     12.1±0.04ms       10.4±0.2ms     0.86 …
```
=> PERF: eliminate unnecessary ravel for median with order="F", speedup of up to 2x

.github/workflows/pythonpackage.yml
Seems the default image doesn't set up the appropriate MSVC install for use with python, remove for now
=> BLD: remove windows build from GitHub Actions as MSVC is not set up properly

asv_bench/benchmarks/move.py, asv_bench/benchmarks/nonreduce_axis.py
These are the last modules missing `asv` coverage - a comparison against `v1.2.0` shows no regressions
=> BENCH: add asv benchmarks for bn.move and bn.nonreduce_axis

readthedocs.yml
RTD doesn't attempt `python setup.py build` prior to building docs, so attempt to force that here.
=> DOC: Add readthedocs.yml to help RTD build our docs

MANIFEST.in
Fix compile errors when building Bottleneck-1.3.0rc1 with msvc on Windows using the source distribution on PyPI:
```
bottleneck/src/reduce.c(2388): error C2143: syntax error: missing ')' before '('
bottleneck/src/reduce.c(2388): error C2091: function returns function
bottleneck/src/reduce.c(2388): error C2143: syntax error: missing ')' before 'string'
bottleneck/src/reduce.c(2388): error C2143: syntax error: missing '{' before 'string'
bottleneck/src/reduce.c(2388): error C2059: syntax error: 'string'
...
```
=> Do not include bn_config.h in source distribution

asv_bench/benchmarks/memory.py, bottleneck/src/reduce_template.c
Partial revert of #248, resolves #276.
`asv find` identified #248 as the cause of the regression:
```
·· Installing 2b9c661e <v1.3.0rc1~45> into conda-py3.6-numpy1.16-CCgcc-CXXg++
·· Benchmarking conda-py3.6-numpy1.16-CCgcc-CXXg++
··· memory.Memory.peakmem_nanmedian                                                                                                                                                           206M
· Greatest regression found: 2b9c661e <v1.3.0rc1~45>
```
The issue occurs when invoking `nanmedian` with `axis=None` (the default) and results in a memory leak. The fix results in constant memory usage.
=> BUG: fix memory leak in nanmedian with axis=None

bottleneck/src/iterators.h, bottleneck/src/reduce_template.c
A couple speedups:
- `bn.median()` buffer creation now early exits even sooner if a `np.NaN` is encountered.
- 'bn.median()` buffer creation is now vectorized for integer inputs
=> PERF: Median speedups

.github/workflows/pythonpackage.yml, .travis.yml, README.rst, appveyor.yml, asv_bench/asv.conf.json, setup.py
As I have received no objections on the mailing list or in #287, adopt and implement NEP 29 (https://numpy.org/neps/nep-0029-deprecation_policy.html)
=> DEPR: Adopt NEP 29, remove py2.7 and py3.5 from supported versions

bottleneck/src/iterators.h, bottleneck/src/nonreduce_template.c, bottleneck/tests/nonreduce_test.py
Fix and test an issue with `bn.replace(arr[::2], ...)` style calls.
=> Fix bug in replace on views with strides different than underlying array

bottleneck/src/reduce_template.c
Improve performance of `bn.nansum` for `int64/int32` in reduction operations.
```
[23332ea7]       [d6f40cff]
<nansum_faster~1>       <nansum_faster>
-      5.71±0.1ms       5.04±0.1ms     0.88  reduce.Time1DReductions.time_nansum('int64', (10000000,)) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-         508±6μs          411±7μs     0.81  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'F', None) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-         512±5μs         414±20μs     0.81  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'C', None) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-     3.22±0.04ms      2.53±0.03ms     0.78 …
```
=> PERF: improve performance of nansum for integers

bottleneck/benchmark/bench.py
A few separate improvements to the `bn.bench()` function:
* Speed up bulk testing by caching input arrays
* Add fast/slow cases to `anynan`/`allnan`
* Add `axis=None` case to default runs
=> Improvements to bn.bench()

bottleneck/tests/nonreduce_axis_test.py
These tests were inadvertently disabled as part of the switch from nose to pytest; re-enable them now.
=> TST: re-enable nonreduce_axis argument exception tests

.github/workflows/pythonpackage.yml, bottleneck/tests/test_template.py
Now that py2.7 and py3.5 have been dropped, we can (hopefully) use Github Actions to run the test suite on windows.
Separately, turn on py3.8 tests on OSX now that it is available.
=> TST: use Github Actions for Windows runs as well as OSX with 3.8

bottleneck/src/reduce_template.c
Add some additional typing and do loop forward rather than reverse
```
$ asv compare upstream/master HEAD -s --sort ratio --only-changed
[595cdfd1]       [56337059]
<actions>        <nanarg_ints>
-       98.7±10μs       89.6±0.8μs     0.91  reduce.Time1DReductions.time_nanargmax('float64', (100000,)) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-      1.09±0.3μs         987±10ns     0.91  reduce.Time1DReductions.time_nanargmin('float64', (1000,)) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        252±20μs          228±1μs     0.90  reduce.Time1DReductions.time_nanargmax('float64', (100000,)) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-     1.03±0.04μs         926±20ns     0.90  reduce.Time1DReductions.time_nanargmin('int32', (1000,)) …
```
=> PERF: do nanargmin/max in-order for integer dtypes

bottleneck/src/reduce_template.c
Up to 3x improvement, though certain combinations under clang see a slight slowdown.
```
$ asv compare HEAD^ HEAD -s --sort ratio --only-changed -f 1.1
[8106e742]       [45940427]
<nanarg_ints>       <nanmin_speedup>
-        276±30μs          236±3μs     0.86  reduce.Time2DReductions.time_nanmin('int32', (1000, 1000), 'F', None) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-        639±20μs         323±40μs     0.51  reduce.Time2DReductions.time_nanmax('int32', (1000, 1000), 'F', 0) [T470/conda-py3.7-numpy1.16-CCclang-CXXclang++]
-        700±10μs         325±40μs     0.46  reduce.Time2DReductions.time_nanmax('int32', (1000, 1000), 'C', 1) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        685±40μs         316±30μs     0.46 …
```
=> PERF: speed up nanmin/max with non-null axis for int32

bottleneck/src/iterators.h, bottleneck/src/reduce_template.c
Add specialized cases for contiguous 2D arrays in nanmin/max, which yield some solid speedups:
```
[37110cf7]       [5be4d6d4]
<nanmin~1>       <nanmin>  
-     1.45±0.08ms         729±50μs     0.50  reduce.Time2DReductions.time_nanmax('float64', (1000, 1000), 'F', 0) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-     1.44±0.03ms         650±10μs     0.45  reduce.Time2DReductions.time_nanmax('float64', (1000, 1000), 'C', 1) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-       829±200μs        357±100μs     0.43  reduce.Time2DReductions.time_nanmax('float32', (1000, 1000), 'C', 1) [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-      2.25±0.1ms        899±100μs     0.40 …
```
=> PERF: optimize for contiguous 2D nanmin/nanmax, speedups of up to 12x

bottleneck/src/reduce_template.c
Significant performance improvement for `axis=None` cases, particularly with `float32`
```
$ asv compare upstream/master HEAD -s --sort ratio
Benchmarks that have improved:
[98b59df2]       [22d46a8e]
<nanmin~1>       <anynan_reduce>
-         559±8ns          502±5ns     0.90  reduce.TimeAnyNan2D.time_anynan('int32', (1000, 1000), 'C', 1, 'fast') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        850±20μs          757±4μs     0.89  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'F', None, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-         876±3μs          777±5μs     0.89  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'C', 1, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-CXXg++]
-        742±30μs          655±7μs     0.88 …
```
=> PERF: improve anynan reduction performance by up to 4x on float32

asv_bench/asv.conf.json
I'm seeing a fair amount of compiler version-connected performance regressions. Specify major version numbers for help tracking these down.
=> BENCH: explicitly declare benchmarked gcc/clang versions

.travis.yml, tools/travis/conda_setup.sh
Now that we're testing on arm64, add ppc64le as well.
=> BLD: begin running tests for ppc64le architecture

tools/travis/conda_install.sh, tools/travis/conda_setup.sh
It appears Archiconda has been superseded by Miniforge, which is aiming for upstreaming with conda generally. Switch to Miniforge and de-dupe some of the installer logic.
cc @odidev
=> BLD: Switch from Archiconda to Miniforge for aarch64

bottleneck/tests/reduce_test.py
Increase the number of examples generated to 500 to speed up counterfactual finding.
=> TST: increase number of hypothesis examples per test run to 500

pyproject.toml
=> BLD: add explicit py38 numpy dependency

.travis.yml, bottleneck/src/bn_config.py, bottleneck/src/reduce_template.c, setup.py, tools/travis/bn_setup.sh
SSE2 is pretty much universal, so start explicitly invoking it as compilers don't seem to want to use it for `allnan`/`anynan`. 
Speedup is sufficient to bring us to parity with numpy in the slow case, which means we are now strictly better than numpy here. Still need to implement for `axis != None`, but looking very promising:
```
asv compare HEAD^ HEAD -s --sort ratio --only-changed
[61eea5ab]       [ff4ee4b4]
<ppc64le>                  
-        262±10μs          224±9μs     0.86  reduce.TimeAllNan2D.time_allnan('float32', (1000, 1000), 'F', None, 'slow') [T470/conda-py3.7-numpy1.16-CCclang-9-CXXclang++-9]
-        778±40μs          604±9μs     0.78  reduce.TimeAnyNan2D.time_anynan('float64', (1000, 1000), 'F', None, 'slow') …
```
=> PERF: introduce SSE2 implementations of allnan/anynan, ~30% speedup

bottleneck/src/reduce_template.c
Get up to ~6x speedup for `nansum` on integer inputes with non-null `axis`.
```
[7ac219a0]       [7988b9f0]
<int_nansum~1>       <int_nansum>
-        571±10μs         380±40μs     0.67  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'F', 0) [T470/conda-py3.7-numpy1.16-CCclang-9-CXXclang++-9]
-         785±8μs         513±50μs     0.65  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'F', 0) [T470/conda-py3.7-numpy1.16-CCgcc-8-CXXg++-8]
-         571±9μs         372±10μs     0.65  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'C', 1) [T470/conda-py3.7-numpy1.16-CCclang-9-CXXclang++-9]
-         778±8μs         483±80μs     0.62 …
```
=> PERF: speed up nansum for integer inputs with axis != None by up to ~6x

bottleneck/src/reduce_template.c
Handle the transpose case in `anynan()`/`allnan()`. Speedups of up to 4x:
```
$ asv compare HEAD^ HEAD -s --sort ratio
Benchmarks that have improved:
[8b587c5c]       [fc95c3d5]
<anynan_sse2~1>       <anynan_sse2>
-        409±90ns          366±9ns     0.90  reduce.TimeAllNan2D.time_allnan('int64', (1000, 1000), 'C', None, 'fast') [T470/conda-py3.7-numpy1.16-CCgcc-9-CXXg++-9]
-        602±60ns         536±20ns     0.89  reduce.TimeAnyNan2D.time_anynan('int32', (1000, 1000), 'C', 0, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-8-CXXg++-8]
-        610±60ns         542±20ns     0.89  reduce.TimeAnyNan2D.time_anynan('int64', (1000, 1000), 'C', 0, 'slow') [T470/conda-py3.7-numpy1.16-CCgcc-9-CXXg++-9]
-      9.02±0.3μs      7.99±0.07μs     0.89 …
```
=> PERF: optimize anynan/allnan with transpose axis

bottleneck/src/bottleneck.h, bottleneck/src/reduce_template.c, bottleneck/tests/reduce_test.py
Add hypothesis testing for `bn.reduce.ss` with integer inputs and resolve some discrepancies. Comes with a performance hit, but further optimization is possible.
Float inputs require pairwise summation to get an exact match.
```
[f1d14dc2]       [b21e3c30]
<bn_isnan~1>       <ss>      
-        63.6±2μs       54.8±0.9μs     0.86  reduce.Time1DReductions.time_ss('int64', (100000,)) [T470/conda-py3.7-numpy1.16-CCgcc-7-CXXg++-7]
-      8.10±0.5ms       6.96±0.4ms     0.86  reduce.Time1DReductions.time_ss('int64', (10000000,)) [T470/conda-py3.7-numpy1.16-CCgcc-8-CXXg++-8]
-       964±200ns          787±7ns     0.82  reduce.Time1DReductions.time_ss('int64', (1000,)) …
```
=> BUG: match behavior of scipy.stats.ss for int32 inputs

README.rst, bottleneck/src/bn_config.py, bottleneck/tests/docker/centos_7_min_deps/Dockerfile, bottleneck/tests/docker/centos_8_min_deps/Dockerfile, bottleneck/tests/docker/release_tests.sh, bottleneck/tests/docker/ubuntu_devel_min_deps/Dockerfile, bottleneck/tests/docker/ubuntu_lts_min_deps/Dockerfile, doc/source/index.rst, doc/source/installing.rst, setup.py
Given our lack of wheels, installation is more complex than some other projects. Attempt to improve the user experience in a few ways:
- Add dedicated installation page in documentation
- Do a test compile to see if a compiler and/or Python development libraries are even available, and point users to installation page if not.
- Add explicit Docker-based tests for minimum installation dependencies for a few OSes
- Specify the C standard used when compiling under `gcc=4.8` or lower, which is the default on RHEL/CentOS 7
cc #281
=> Make installation process more robust for users

.github/workflows/pythonpackage.yml, .travis.yml, Makefile, asv_bench/benchmarks/memory.py, asv_bench/benchmarks/nonreduce.py, asv_bench/benchmarks/reduce.py, bottleneck/__init__.py, bottleneck/benchmark/bench.py, bottleneck/benchmark/bench_detailed.py, bottleneck/src/bn_config.py, bottleneck/src/bn_template.py, bottleneck/tests/list_input_test.py, bottleneck/tests/move_test.py, bottleneck/tests/nonreduce_axis_test.py, bottleneck/tests/nonreduce_test.py, bottleneck/tests/reduce_test.py, bottleneck/tests/scalar_input_test.py, bottleneck/tests/test_template.py, bottleneck/tests/util.py, doc/source/conf.py, doc/sphinxext/contributors.py, setup.cfg, tools/travis/bn_setup.sh
Set up `isort` to automatically run and configure to be consistent with `black`. Configure via `Makefile` and to run as part of Github Actions and Travis CI.
=> STY: run isort as part of CI and run on remaining files

pyproject.toml, setup.py
Currently the pyproject.toml file is missing a Numpy version for Python 3.8. Rather than add this, I've switched this file to use the [oldest-supported-numpy](https://github.com/scipy/oldest-supported-numpy) meta-package which is equivalent to specifying all the environment markers (see the README for that project) but means that the pyproject.toml file here doesn't need to be updated in future when a new version of Python is released since this just requires a new release of oldest-supported-numpy.
It looks like bottleneck requires Python 3.6 based on the classifiers, so I've also added an explicit ``python_requires`` which will prevent older Python versions from downloading newer releases.
=> Use oldest-supported-numpy in pyproject.toml and explicitly require Python 3.6

.github/workflows/pythonpackage.yml, .travis.yml, bottleneck/__init__.py, bottleneck/src/bn_config.py, bottleneck/tests/util.py, doc/sphinxext/contributors.py, setup.cfg, tools/travis/bn_setup.sh
`isort 5.x` has some major changes, so adjust our config and perform a bulk reformat.
=> CLN: reformat with isort 5.x and black

.github/workflows/pythonpackage.yml, .travis.yml, README.rst, appveyor.yml, bottleneck/_pytesttester.py, bottleneck/tests/common.py, bottleneck/tests/input_modification_test.py, bottleneck/tests/reduce_test.py, bottleneck/tests/util.py, setup.py, tools/travis/bn_setup.sh
Resolve #352 by adding a `bottleneck[test]` extra that can be installed with:
pip install bottleneck[test]
Or, if working off master:
pip install .[test]
Also, document this in `README`.
=> BLD: make test dependencies part of extras and use on CI

bottleneck/src/move_template.c, bottleneck/src/nonreduce_axis_template.c, bottleneck/src/nonreduce_template.c, bottleneck/src/reduce_template.c
Close #351 by decref'ing `a` before returning the slow path.
=> BUG: decref array when falling back to slow call

bottleneck/src/reduce_template.c
Significant speedup in contiguous case:
```
$ asv compare HEAD^ HEAD -s --only-changed --sort ratio
[1975fa0c]       [143f52fb]
<int_nansum~1>       <int_nansum_contig>
-         695±5μs          422±1μs     0.61  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'F', 0)
-         699±3μs          422±1μs     0.60  reduce.Time2DReductions.time_nansum('int64', (1000, 1000), 'C', 1)
```
=> PERF: int nansum contiguous case

bottleneck/slow/move.py
numpy 1.20.0 deprecates `np.bool` etc, see.: https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated. I found one usage of this in bottleneck, that causes some [warnings in xarray](https://github.com/pydata/xarray/runs/1653359233#step:7:369).
=> use bool instead of np.bool

bottleneck/src/bn_config.py
Don't use sys.version[:3] which doesn't work on "3.10.0a6 (...)"
string.
=> Fix get_python_header_include() for Python 3.10

pyproject.toml, setup.py
This PR does a few things:
* Since Numpy 1.25, the Numpy C API is backward-compatible and ``oldest-supported-numpy`` is no longer needed (see https://numpy.org/doc/stable/dev/depending_on_numpy.html#build-time-dependency for example), so we can get rid of ``oldest-supported-numpy`` in the build-time dependencies in ``pyproject.toml`` and just use ``numpy``
* As discussed in https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395, packages that depend on the Numpy C API will need new wheels compiled against Numpy 2.0 in order to be compatible with both Numpy 1.x and 2.x. These wheels should ideally be released *before* Numpy 2.0 is released. As Numpy 2.0.0rc1 is out and the ABI is guaranteed to no longer change, the [recommendation](https://github.com/numpy/numpy/issues/24300#is …
=> Update Numpy build-time requirement (time sensitive)

setup.py
The `Requires` field was deprecated with [PEP
345](https://peps.python.org/pep-0345/#summary-of-differences-from-pep-314) circa 2005.  [PEP
566](https://peps.python.org/pep-0566/#summary-of-differences-from-pep-345) circa 2017 introduced version 2.1 (used by bottleneck) of the metadata specification without any mention of `Requires`.
This is a problem because a tool working with Python packages might reasonably validate that the fields in the package metadata are valid per the specification.
=> remove 'requires' metadata field deprecated for ~19 years

.github/workflows/ci.yml, bottleneck/slow/move.py, bottleneck/slow/nonreduce_axis.py, pyproject.toml, setup.py
Follow up of https://github.com/pydata/bottleneck/pull/449#issuecomment-2100314258
=> Test with numpy 2.0.0rc1 and fix API changes of np.array()'s copy kwarg

pyproject.toml
The rule is <N+3, and numpy 2.2.x is out, so the bound should be <2.5.
Also add a `pytest.ini` file that will turn deprecation warnings in the test suite into errors. This will catch any deprecations from `numpy` or `python`, so that they can be fixed in time. Having the test suite run deprecation-warning-free is the guarantee that the <N+3 upper bound will work. The `pytest.ini` contents are derived from what NumPy and SciPy also use.
=> MAINT: update maximum numpy version to build against

.github/workflows/ci.yml
20.04 is now failing, it is past the end of its announced deprecation period, see https://github.com/actions/runner-images/issues/11101
=> CI: bump ubuntu-20.04 to 22.04 in CI jobs

.github/workflows/ci.yml, bottleneck/conftest.py, bottleneck/src/move_template.c, bottleneck/src/nonreduce_axis_template.c, bottleneck/src/nonreduce_template.c, bottleneck/src/reduce_template.c, bottleneck/tests/memory_test.py, bottleneck/tests/test_template.py
This PR enables free-threading builds of bottleneck, available from Python 3.13 onwards, this new distribution allows Python packages to leverage true parallel support, as the GIL is now optional. 
In particular, this PR performs the following checks:
=> ENH: enable CPython free-threading support

.github/bottleneck-action/action.yml, .github/workflows/ci.yml
This modernizes the CI setup to do the following:
- Test jobs that runs on PRs:
- Adds macOS arm64
- Adds Linux aarch64
- Removes running duplicate jobs on `ubuntu-22.04` and `ubuntu-latest` (both x86-64, not useful)
- Removes running jobs for every single minor Python version, but rather runs mininum (3.9), maximum (3.13) supported versions + free-threading (3.13t)
- Refactors the test matrix so it's easier to read (no more  `exclude`) jobs
- Wheel build jobs (logs from a wheel build run [here](https://github.com/rgommers/bottleneck/actions/runs/14933404774/job/41955095607)):
- Restores macOS x86-64 (those went missing from recent releases due to `macos-latest` switching from x86-64 to arm64, see e.g. https://pypi.org/project/Bottleneck/1.4.2/#files)
- Adds Linux aarch64
- Removes 32-bit …
=> CI: add macOS arm64, Linux aarch, remove i686 wheels, trim test matrix

MANIFEST.in, pyproject.toml, setup.py
This PR fixes some build warnings that were visible in CI logs, as well as two mistakes in `pyproject.toml`. In addition it would be good to start using the `[project]` section of `pyproject.toml` (because `setuptools` is discouraging/deprecation/removing alternatives, see [here](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setuppy-discouraged)), but that's more involved so left for another PR.
The warnings were:
```
warning: no files found matching 'tox.ini'
Running command Preparing metadata (pyproject.toml)
/tmp/pip-build-env-ua_ysm8p/overlay/lib/python3.12/site-packages/setuptools/dist.py:761: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!
********************************************************************************
Please consider removing …
```
=> Fix some build warnings and mistakes in pyproject.toml

.github/workflows/ci.yml
This is a follow-up to gh-481, which moved to cibuildwheel 3.x which removed PyPy from the default set of wheels being built.
=> MAINT: fix warning about `pp_*` skip selector for PyPy wheels not being needed
